CREATE DATABASE yeti_cave

DEFAULT CHARACTER SET utf8;
USE yeti_cave;

CREATE TABLE category (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) UNIQUE,
  code VARCHAR(64) UNIQUE
);

CREATE TABLE lot (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED,
  cat_id SMALLINT UNSIGNED,
  winner_id INT UNSIGNED,
  date_add TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  name VARCHAR(256),
  description VARCHAR(1000),
  img VARCHAR(512),
  start_price INT UNSIGNED,
  completion_date TIMESTAMP,
  bet_rate TINYINT UNSIGNED
);

CREATE TABLE rate (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED,
    lot_id INT UNSIGNED,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    rate INT UNSIGNED
);

CREATE TABLE user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    lot_id INT UNSIGNED,
    rate_id INT UNSIGNED,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    email VARCHAR(128) NOT NULL UNIQUE,
    user_name VARCHAR(128) NOT NULL UNIQUE,
    password VARCHAR(128),
    avatar VARCHAR(512),
    contacts VARCHAR(1000)
);
